services:
  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pc
      POSTGRES_PASSWORD: password
      PG_DATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
