-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.client
(
    user_id integer NOT NULL,
    client_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    website character varying(300) COLLATE pg_catalog."default",
    CONSTRAINT client_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    user_id integer NOT NULL,
    employee_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    employee_role character(1) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT employee_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.employee_project_bridge
(
    user_id integer NOT NULL,
    project_lead_id integer NOT NULL,
    project_id integer NOT NULL,
    CONSTRAINT employee_project_bridge_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.project
(
    project_id integer NOT NULL,
    client_id integer NOT NULL,
    project_lead_id integer NOT NULL,
    CONSTRAINT project_pkey PRIMARY KEY (project_id)
);

CREATE TABLE IF NOT EXISTS public.task
(
    project_id integer NOT NULL,
    task_id integer NOT NULL,
    description character varying(500) COLLATE pg_catalog."default" NOT NULL,
    deadline date NOT NULL,
    start_date date NOT NULL,
    expected_work_hours double precision NOT NULL,
    progress_in_work_hours double precision DEFAULT 0,
    CONSTRAINT task_pkey PRIMARY KEY (task_id)
);

CREATE TABLE IF NOT EXISTS public.time_off
(
    time_off_id integer NOT NULL,
    employee_id integer NOT NULL,
    start_date date,
    end_date date,
    status character(1) COLLATE pg_catalog."default" NOT NULL,
    reason character varying(500) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT time_off_pkey PRIMARY KEY (time_off_id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    user_id integer NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.video_training
(
    video_id integer NOT NULL,
    video_link character varying(300) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT video_training_pkey PRIMARY KEY (video_id)
);
END;