server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: pc
    password: password

  jpa:
    hibernate:
      #change to update for production.
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true